# PHPのバージョンは8.1
runtime: php81
# スタンダード環境を指定
env: standard


runtime_config:
  document_root: public
  php_version: 8.1


# CSSとJS
handlers:
- url: /css
  static_dir: public/css
- url: /js
  static_dir: public/js


automatic_scaling:
  min_idle_instances: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 80


env_variables:
  # ログのエラーが出ないようにするための記述
  LOG_CHANNEL: stderr
  # キャッシュのエラーが出ないようにするための記述
  CACHE_DIRECTORY: /tmp/laravel/cache
  SESSION_DRIVER: cookie
  APP_STORAGE: /tmp
  # Cloud SQL
  DB_DATABASE: example_app
  DB_USERNAME: root
  DB_PASSWORD: root
  DB_SOCKET: "/cloudsql/t-project-gcp:asia-northeast1:test-instance"


# デプロイ時のcomposerのバージョン
build_env_variables:
  GOOGLE_COMPOSER_VERSION: 2.2.1
